#include "pinggen/llvm_ir.hpp"

#include <sstream>

namespace pinggen {

std::string LLVMIRGenerator::generate(const Program& program) {
    globals_.clear();
    functions_.clear();
    body_.clear();
    variables_.clear();
    variable_types_.clear();
    function_return_types_.clear();
    register_counter_ = 0;
    string_counter_ = 0;
    label_counter_ = 0;
    current_function_name_.clear();
    current_return_type_ = ValueType::Void;

    globals_ += "@.fmt.int = private unnamed_addr constant [6 x i8] c\"%lld\\0A\\00\"\n";
    globals_ += "@.fmt.str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n";

    for (const auto& function : program.functions) {
        function_return_types_[function.name] = function.return_type == ValueType::Void && function.name == "main"
                                                    ? ValueType::Int
                                                    : function.return_type;
    }

    std::ostringstream out;
    out << "; generated by pinggen\n";
    out << "declare i32 @printf(ptr, ...)\n\n";

    for (const auto& function : program.functions) {
        reset_function_state();
        current_function_name_ = function.name;
        current_return_type_ = function_return_types_.at(function.name);

        std::ostringstream signature;
        signature << "define " << (function.name == "main" ? "i32" : llvm_type(current_return_type_)) << " @" << function.name
                  << "(";
        for (std::size_t i = 0; i < function.params.size(); ++i) {
            if (i != 0) {
                signature << ", ";
            }
            signature << llvm_type(function.params[i].type) << " %arg" << i;
        }
        signature << ") {\n";

        for (std::size_t i = 0; i < function.params.size(); ++i) {
            const auto& param = function.params[i];
            const std::string storage = next_register();
            body_ += "  " + storage + " = alloca " + llvm_type(param.type) + "\n";
            body_ += "  store " + llvm_type(param.type) + " %arg" + std::to_string(i) + ", ptr " + storage + "\n";
            variables_[param.name] = storage;
            variable_types_[param.name] = param.type;
        }

        const bool has_return = emit_block(function.body);
        if (!has_return) {
            if (function.name == "main") {
                body_ += "  ret i32 0\n";
            } else if (current_return_type_ == ValueType::Void) {
                body_ += "  ret void\n";
            }
        }

        signature << body_;
        signature << "}\n\n";
        functions_ += signature.str();
    }

    out << globals_ << "\n";
    out << functions_;
    return out.str();
}

std::string LLVMIRGenerator::emit_string_constant(const std::string& value) {
    const std::string name = next_string_name();
    const std::size_t byte_len = value.size() + 1;
    std::ostringstream out;
    out << "@" << name << " = private unnamed_addr constant [" << byte_len << " x i8] c\"" << escape_bytes(value)
        << "\\00\"\n";
    globals_ += out.str();
    return name + "|" + std::to_string(byte_len);
}

TypedIRValue LLVMIRGenerator::emit_expr(const Expr& expr) {
    if (const auto* node = dynamic_cast<const IntegerExpr*>(&expr)) {
        return {std::to_string(node->value), ValueType::Int};
    }
    if (const auto* node = dynamic_cast<const BoolExpr*>(&expr)) {
        return {node->value ? "1" : "0", ValueType::Bool};
    }
    if (const auto* node = dynamic_cast<const StringExpr*>(&expr)) {
        const std::string constant = emit_string_constant(node->value);
        const auto sep = constant.find('|');
        const std::string global_name = constant.substr(0, sep);
        const std::size_t len = static_cast<std::size_t>(std::stoull(constant.substr(sep + 1)));
        const std::string reg = next_register();
        body_ += "  " + reg + " = getelementptr inbounds [" + std::to_string(len) + " x i8], ptr @" + global_name +
                 ", i64 0, i64 0\n";
        return {reg, ValueType::String};
    }
    if (const auto* node = dynamic_cast<const VariableExpr*>(&expr)) {
        const std::string& addr = variables_.at(node->name);
        const ValueType type = variable_types_.at(node->name);
        const std::string reg = next_register();
        body_ += "  " + reg + " = load " + llvm_type(type) + ", ptr " + addr + "\n";
        return {reg, type};
    }
    if (const auto* node = dynamic_cast<const BinaryExpr*>(&expr)) {
        const TypedIRValue left = emit_expr(*node->left);
        const TypedIRValue right = emit_expr(*node->right);
        const std::string reg = next_register();

        if (node->op == "==" || node->op == "!=") {
            const std::string cmp = node->op == "==" ? "eq" : "ne";
            body_ += "  " + reg + " = icmp " + cmp + " " + llvm_type(left.type) + " " + left.ir + ", " + right.ir + "\n";
            return {reg, ValueType::Bool};
        }

        std::string op;
        if (node->op == "+") op = "add";
        if (node->op == "-") op = "sub";
        if (node->op == "*") op = "mul";
        if (node->op == "/") op = "sdiv";
        body_ += "  " + reg + " = " + op + " i64 " + left.ir + ", " + right.ir + "\n";
        return {reg, ValueType::Int};
    }
    if (const auto* node = dynamic_cast<const CallExpr*>(&expr)) {
        if (node->callee == "io::println") {
            const TypedIRValue arg = emit_expr(*node->args[0]);
            if (arg.type == ValueType::Int) {
                const std::string fmt_reg = next_register();
                const std::string call_reg = next_register();
                body_ += "  " + fmt_reg + " = getelementptr inbounds [6 x i8], ptr @.fmt.int, i64 0, i64 0\n";
                body_ += "  " + call_reg + " = call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", i64 " + arg.ir + ")\n";
            } else {
                const std::string fmt_reg = next_register();
                const std::string call_reg = next_register();
                body_ += "  " + fmt_reg + " = getelementptr inbounds [4 x i8], ptr @.fmt.str, i64 0, i64 0\n";
                body_ += "  " + call_reg + " = call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", ptr " + arg.ir + ")\n";
            }
            return {"0", ValueType::Void};
        }

        std::vector<TypedIRValue> args;
        args.reserve(node->args.size());
        for (const auto& arg : node->args) {
            args.push_back(emit_expr(*arg));
        }

        const ValueType return_type = function_return_types_.at(node->callee);
        std::string call_args;
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (i != 0) {
                call_args += ", ";
            }
            call_args += llvm_type(args[i].type) + " " + args[i].ir;
        }

        if (return_type == ValueType::Void) {
            body_ += "  call void @" + node->callee + "(" + call_args + ")\n";
            return {"0", ValueType::Void};
        }

        const std::string reg = next_register();
        body_ += "  " + reg + " = call " + llvm_type(return_type) + " @" + node->callee + "(" + call_args + ")\n";
        return {reg, return_type};
    }

    return {"0", ValueType::Void};
}

bool LLVMIRGenerator::emit_block(const std::vector<std::unique_ptr<Stmt>>& body) {
    for (const auto& stmt : body) {
        if (emit_stmt(*stmt)) {
            return true;
        }
    }
    return false;
}

bool LLVMIRGenerator::emit_stmt(const Stmt& stmt) {
    if (const auto* node = dynamic_cast<const LetStmt*>(&stmt)) {
        const TypedIRValue value = emit_expr(*node->initializer);
        const std::string storage = next_register();
        body_ += "  " + storage + " = alloca " + llvm_type(value.type) + "\n";
        body_ += "  store " + llvm_type(value.type) + " " + value.ir + ", ptr " + storage + "\n";
        variables_[node->name] = storage;
        variable_types_[node->name] = value.type;
        return false;
    }
    if (const auto* node = dynamic_cast<const AssignStmt*>(&stmt)) {
        const TypedIRValue value = emit_expr(*node->value);
        const ValueType type = variable_types_.at(node->name);
        body_ += "  store " + llvm_type(type) + " " + value.ir + ", ptr " + variables_.at(node->name) + "\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const ExprStmt*>(&stmt)) {
        emit_expr(*node->expr);
        return false;
    }
    if (const auto* node = dynamic_cast<const IfStmt*>(&stmt)) {
        const TypedIRValue condition = emit_expr(*node->condition);
        const std::string then_label = next_label("if_then");
        const std::string else_label = next_label("if_else");
        const std::string end_label = next_label("if_end");
        body_ += "  br i1 " + condition.ir + ", label %" + then_label + ", label %" + else_label + "\n";

        body_ += then_label + ":\n";
        const bool then_returns = emit_block(node->then_body);
        if (!then_returns) {
            body_ += "  br label %" + end_label + "\n";
        }

        body_ += else_label + ":\n";
        const bool has_else = !node->else_body.empty();
        bool else_returns = false;
        if (has_else) {
            else_returns = emit_block(node->else_body);
        }
        if (!else_returns) {
            body_ += "  br label %" + end_label + "\n";
        }

        if (!(then_returns && has_else && else_returns)) {
            body_ += end_label + ":\n";
        }
        return then_returns && has_else && else_returns;
    }
    if (const auto* node = dynamic_cast<const WhileStmt*>(&stmt)) {
        const std::string cond_label = next_label("while_cond");
        const std::string body_label = next_label("while_body");
        const std::string end_label = next_label("while_end");

        body_ += "  br label %" + cond_label + "\n";
        body_ += cond_label + ":\n";
        const TypedIRValue condition = emit_expr(*node->condition);
        body_ += "  br i1 " + condition.ir + ", label %" + body_label + ", label %" + end_label + "\n";

        body_ += body_label + ":\n";
        const bool body_returns = emit_block(node->body);
        if (!body_returns) {
            body_ += "  br label %" + cond_label + "\n";
            body_ += end_label + ":\n";
            return false;
        }

        body_ += end_label + ":\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const ReturnStmt*>(&stmt)) {
        if (!node->value) {
            if (current_function_name_ == "main") {
                body_ += "  ret i32 0\n";
            } else if (current_return_type_ == ValueType::Void) {
                body_ += "  ret void\n";
            } else if (current_return_type_ == ValueType::Bool) {
                body_ += "  ret i1 0\n";
            } else {
                body_ += "  ret i64 0\n";
            }
            return true;
        }

        const TypedIRValue value = emit_expr(*node->value);
        if (current_function_name_ == "main") {
            const std::string reg = next_register();
            body_ += "  " + reg + " = trunc i64 " + value.ir + " to i32\n";
            body_ += "  ret i32 " + reg + "\n";
        } else {
            body_ += "  ret " + llvm_type(value.type) + " " + value.ir + "\n";
        }
        return true;
    }
    return false;
}

std::string LLVMIRGenerator::llvm_type(ValueType type) const {
    switch (type) {
        case ValueType::Int: return "i64";
        case ValueType::Bool: return "i1";
        case ValueType::String: return "ptr";
        case ValueType::Void: return "void";
    }
    return "void";
}

std::string LLVMIRGenerator::next_label(const std::string& prefix) {
    return prefix + "." + std::to_string(++label_counter_);
}

void LLVMIRGenerator::reset_function_state() {
    body_.clear();
    variables_.clear();
    variable_types_.clear();
    register_counter_ = 0;
}

std::string LLVMIRGenerator::next_register() {
    return "%" + std::to_string(++register_counter_);
}

std::string LLVMIRGenerator::next_string_name() {
    return ".str." + std::to_string(++string_counter_);
}

std::string LLVMIRGenerator::escape_bytes(const std::string& value) {
    std::ostringstream out;
    for (unsigned char c : value) {
        switch (c) {
            case '\n': out << "\\0A"; break;
            case '\t': out << "\\09"; break;
            case '\"': out << "\\22"; break;
            case '\\': out << "\\5C"; break;
            default:
                if (c >= 32 && c <= 126) {
                    out << static_cast<char>(c);
                } else {
                    const char* digits = "0123456789ABCDEF";
                    out << '\\' << digits[(c >> 4) & 0xF] << digits[c & 0xF];
                }
        }
    }
    return out.str();
}

}  // namespace pinggen
