#include "pinggen/llvm_ir.hpp"

#include <sstream>

namespace pinggen {

std::string LLVMIRGenerator::generate(const Program& program) {
    globals_.clear();
    body_.clear();
    variables_.clear();
    variable_types_.clear();
    register_counter_ = 0;
    string_counter_ = 0;

    globals_ += "@.fmt.int = private unnamed_addr constant [5 x i8] c\"%lld\\0A\\00\"\n";
    globals_ += "@.fmt.str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n";

    const FunctionDecl* main = nullptr;
    for (const auto& function : program.functions) {
        if (function.name == "main") {
            main = &function;
            break;
        }
    }

    for (const auto& stmt : main->body) {
        emit_stmt(*stmt);
    }

    std::ostringstream out;
    out << "; generated by pinggen\n";
    out << "declare i32 @printf(ptr, ...)\n\n";
    out << globals_ << "\n";
    out << "define i32 @main() {\n";
    out << body_;
    out << "  ret i32 0\n";
    out << "}\n";
    return out.str();
}

std::string LLVMIRGenerator::emit_string_constant(const std::string& value) {
    const std::string name = next_string_name();
    const std::size_t byte_len = value.size() + 1;
    std::ostringstream out;
    out << "@" << name << " = private unnamed_addr constant [" << byte_len << " x i8] c\""
        << escape_bytes(value) << "\\00\"\n";
    globals_ += out.str();
    return name + "|" + std::to_string(byte_len);
}

std::string LLVMIRGenerator::emit_expr(const Expr& expr) {
    if (const auto* node = dynamic_cast<const IntegerExpr*>(&expr)) {
        return std::to_string(node->value) + "|int";
    }
    if (const auto* node = dynamic_cast<const StringExpr*>(&expr)) {
        return emit_string_constant(node->value) + "|string";
    }
    if (const auto* node = dynamic_cast<const VariableExpr*>(&expr)) {
        const std::string addr = variables_.at(node->name);
        const std::string type = variable_types_.at(node->name);
        const std::string reg = next_register();
        if (type == "int") {
            body_ += "  " + reg + " = load i64, ptr " + addr + "\n";
        } else {
            body_ += "  " + reg + " = load ptr, ptr " + addr + "\n";
        }
        return reg + "|" + type;
    }
    if (const auto* node = dynamic_cast<const BinaryExpr*>(&expr)) {
        const std::string left = emit_expr(*node->left);
        const std::string right = emit_expr(*node->right);
        const auto left_sep = left.find('|');
        const auto right_sep = right.find('|');
        const std::string reg = next_register();
        std::string op;
        if (node->op == "+") op = "add";
        if (node->op == "-") op = "sub";
        if (node->op == "*") op = "mul";
        if (node->op == "/") op = "sdiv";
        body_ += "  " + reg + " = " + op + " i64 " + left.substr(0, left_sep) + ", " + right.substr(0, right_sep) + "\n";
        return reg + "|int";
    }
    if (const auto* node = dynamic_cast<const CallExpr*>(&expr)) {
        if (node->callee == "io::println") {
            const std::string arg = emit_expr(*node->args[0]);
            const auto sep = arg.find('|');
            const std::string arg_ir = arg.substr(0, sep);
            const std::string arg_type = arg.substr(sep + 1);
            if (arg_type == "int") {
                const std::string fmt_reg = next_register();
                body_ += "  " + fmt_reg + " = getelementptr inbounds [5 x i8], ptr @.fmt.int, i64 0, i64 0\n";
                body_ += "  call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", i64 " + arg_ir + ")\n";
            } else {
                const auto name_sep = arg_ir.find('|');
                if (name_sep != std::string::npos) {
                    const std::string global_name = arg_ir.substr(0, name_sep);
                    const std::size_t len = static_cast<std::size_t>(std::stoull(arg_ir.substr(name_sep + 1)));
                    const std::string str_reg = next_register();
                    const std::string fmt_reg = next_register();
                    body_ += "  " + str_reg + " = getelementptr inbounds [" + std::to_string(len) + " x i8], ptr @" + global_name + ", i64 0, i64 0\n";
                    body_ += "  " + fmt_reg + " = getelementptr inbounds [4 x i8], ptr @.fmt.str, i64 0, i64 0\n";
                    body_ += "  call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", ptr " + str_reg + ")\n";
                } else {
                    const std::string fmt_reg = next_register();
                    body_ += "  " + fmt_reg + " = getelementptr inbounds [4 x i8], ptr @.fmt.str, i64 0, i64 0\n";
                    body_ += "  call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", ptr " + arg_ir + ")\n";
                }
            }
            return "0|void";
        }
    }
    return "0|void";
}

void LLVMIRGenerator::emit_stmt(const Stmt& stmt) {
    if (const auto* node = dynamic_cast<const LetStmt*>(&stmt)) {
        const std::string storage = next_register();
        const std::string value = emit_expr(*node->initializer);
        const auto sep = value.find('|');
        const std::string value_ir = value.substr(0, sep);
        const std::string type = value.substr(sep + 1);
        if (type == "int") {
            body_ += "  " + storage + " = alloca i64\n";
            body_ += "  store i64 " + value_ir + ", ptr " + storage + "\n";
        } else {
            std::string pointer_ir = value_ir;
            const auto name_sep = value_ir.find('|');
            if (name_sep != std::string::npos) {
                const std::string global_name = value_ir.substr(0, name_sep);
                const std::size_t len = static_cast<std::size_t>(std::stoull(value_ir.substr(name_sep + 1)));
                const std::string str_reg = next_register();
                body_ += "  " + str_reg + " = getelementptr inbounds [" + std::to_string(len) + " x i8], ptr @" + global_name + ", i64 0, i64 0\n";
                pointer_ir = str_reg;
            }
            body_ += "  " + storage + " = alloca ptr\n";
            body_ += "  store ptr " + pointer_ir + ", ptr " + storage + "\n";
        }
        variables_[node->name] = storage;
        variable_types_[node->name] = type;
        return;
    }
    if (const auto* node = dynamic_cast<const AssignStmt*>(&stmt)) {
        const std::string value = emit_expr(*node->value);
        const auto sep = value.find('|');
        if (variable_types_.at(node->name) == "int") {
            body_ += "  store i64 " + value.substr(0, sep) + ", ptr " + variables_.at(node->name) + "\n";
        } else {
            body_ += "  store ptr " + value.substr(0, sep) + ", ptr " + variables_.at(node->name) + "\n";
        }
        return;
    }
    if (const auto* node = dynamic_cast<const ExprStmt*>(&stmt)) {
        emit_expr(*node->expr);
        return;
    }
    if (const auto* node = dynamic_cast<const ReturnStmt*>(&stmt)) {
        if (node->value) {
            const std::string value = emit_expr(*node->value);
            const auto sep = value.find('|');
            body_ += "  ret i32 " + value.substr(0, sep) + "\n";
        } else {
            body_ += "  ret i32 0\n";
        }
    }
}

std::string LLVMIRGenerator::next_register() {
    return "%" + std::to_string(++register_counter_);
}

std::string LLVMIRGenerator::next_string_name() {
    return ".str." + std::to_string(++string_counter_);
}

std::string LLVMIRGenerator::escape_bytes(const std::string& value) {
    std::ostringstream out;
    for (unsigned char c : value) {
        switch (c) {
            case '\n': out << "\\0A"; break;
            case '\t': out << "\\09"; break;
            case '\"': out << "\\22"; break;
            case '\\': out << "\\5C"; break;
            default:
                if (c >= 32 && c <= 126) {
                    out << static_cast<char>(c);
                } else {
                    const char* digits = "0123456789ABCDEF";
                    out << '\\' << digits[(c >> 4) & 0xF] << digits[c & 0xF];
                }
        }
    }
    return out.str();
}

}  // namespace pinggen
