#include "pinggen/llvm_ir.hpp"

#include <sstream>

namespace pinggen {

std::string LLVMIRGenerator::lowered_function_name(const FunctionDecl& function) {
    if (!function.is_method()) {
        return function.name;
    }
    return function.impl_target + "__" + function.name;
}

std::string LLVMIRGenerator::generate(const Program& program) {
    globals_.clear();
    functions_.clear();
    body_.clear();
    structs_.clear();
    struct_field_indices_.clear();
    variables_.clear();
    variable_types_.clear();
    function_return_types_.clear();
    mutating_methods_.clear();
    register_counter_ = 0;
    string_counter_ = 0;
    label_counter_ = 0;
    current_function_name_.clear();
    current_return_type_ = Type::void_type();
    break_labels_.clear();
    continue_labels_.clear();

    globals_ += "@.fmt.int = private unnamed_addr constant [6 x i8] c\"%lld\\0A\\00\"\n";
    globals_ += "@.fmt.str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\"\n";

    std::ostringstream type_defs;
    for (const auto& decl : program.structs) {
        structs_[decl.name] = decl;
        for (std::size_t i = 0; i < decl.fields.size(); ++i) {
            struct_field_indices_[decl.name][decl.fields[i].name] = i;
        }
        type_defs << "%struct." << decl.name << " = type { ";
        for (std::size_t i = 0; i < decl.fields.size(); ++i) {
            if (i != 0) {
                type_defs << ", ";
            }
            type_defs << llvm_type(decl.fields[i].type);
        }
        type_defs << " }\n";
    }

    for (const auto& function : program.functions) {
        function_return_types_[lowered_function_name(function)] =
            function.return_type == Type::void_type() && function.name == "main" ? Type::int_type() : function.return_type;
        mutating_methods_[lowered_function_name(function)] = function.is_mutating_method();
    }

    std::ostringstream out;
    out << "; generated by pinggen\n";
    out << "declare i32 @printf(ptr, ...)\n\n";
    out << "declare void @exit(i32)\n";
    out << "declare i64 @strlen(ptr)\n";
    out << "declare ptr @malloc(i64)\n";
    out << "declare ptr @memcpy(ptr, ptr, i64)\n\n";
    out << emit_concat_helper();
    out << emit_bounds_abort_helper();
    if (!program.structs.empty()) {
        out << type_defs.str() << "\n";
    }

    for (const auto& function : program.functions) {
        reset_function_state();
        current_function_name_ = lowered_function_name(function);
        current_return_type_ = function_return_types_.at(current_function_name_);

        std::ostringstream signature;
        signature << "define " << (function.name == "main" ? "i32" : llvm_type(current_return_type_)) << " @" << current_function_name_
                  << "(";
        for (std::size_t i = 0; i < function.params.size(); ++i) {
            if (i != 0) {
                signature << ", ";
            }
            if (function.is_mutating_method() && i == 0) {
                signature << "ptr %arg" << i;
            } else {
                signature << llvm_type(function.params[i].type) << " %arg" << i;
            }
        }
        signature << ") {\n";

        for (std::size_t i = 0; i < function.params.size(); ++i) {
            const auto& param = function.params[i];
            if (function.is_mutating_method() && i == 0) {
                variables_[param.name] = "%arg" + std::to_string(i);
                variable_types_[param.name] = param.type;
                continue;
            }
            const std::string storage = next_register();
            body_ += "  " + storage + " = alloca " + llvm_type(param.type) + "\n";
            body_ += "  store " + llvm_type(param.type) + " %arg" + std::to_string(i) + ", ptr " + storage + "\n";
            variables_[param.name] = storage;
            variable_types_[param.name] = param.type;
        }

        const bool has_return = emit_block(function.body);
        if (!has_return) {
            if (function.name == "main") {
                body_ += "  ret i32 0\n";
            } else if (current_return_type_ == Type::void_type()) {
                body_ += "  ret void\n";
            }
        }

        signature << body_;
        signature << "}\n\n";
        functions_ += signature.str();
    }

    out << globals_ << "\n";
    out << functions_;
    return out.str();
}

std::string LLVMIRGenerator::emit_concat_helper() const {
    return
        "define ptr @pinggen_concat(ptr %lhs, ptr %rhs) {\n"
        "  %1 = call i64 @strlen(ptr %lhs)\n"
        "  %2 = call i64 @strlen(ptr %rhs)\n"
        "  %3 = add i64 %1, %2\n"
        "  %4 = add i64 %3, 1\n"
        "  %5 = call ptr @malloc(i64 %4)\n"
        "  %6 = call ptr @memcpy(ptr %5, ptr %lhs, i64 %1)\n"
        "  %7 = getelementptr inbounds i8, ptr %5, i64 %1\n"
        "  %8 = call ptr @memcpy(ptr %7, ptr %rhs, i64 %2)\n"
        "  %9 = getelementptr inbounds i8, ptr %5, i64 %3\n"
        "  store i8 0, ptr %9\n"
        "  ret ptr %5\n"
        "}\n\n";
}

std::string LLVMIRGenerator::emit_bounds_abort_helper() const {
    return
        "define void @pinggen_bounds_abort() {\n"
        "  call void @exit(i32 1)\n"
        "  unreachable\n"
        "}\n\n";
}

void LLVMIRGenerator::emit_bounds_check(const std::string& index_ir, std::size_t size) {
    const std::string nonnegative = next_register();
    const std::string within = next_register();
    const std::string ok = next_register();
    const std::string fail_label = next_label("bounds_fail");
    const std::string ok_label = next_label("bounds_ok");
    body_ += "  " + nonnegative + " = icmp sge i64 " + index_ir + ", 0\n";
    body_ += "  " + within + " = icmp slt i64 " + index_ir + ", " + std::to_string(size) + "\n";
    body_ += "  " + ok + " = and i1 " + nonnegative + ", " + within + "\n";
    body_ += "  br i1 " + ok + ", label %" + ok_label + ", label %" + fail_label + "\n";
    body_ += fail_label + ":\n";
    body_ += "  call void @pinggen_bounds_abort()\n";
    body_ += "  unreachable\n";
    body_ += ok_label + ":\n";
}

std::string LLVMIRGenerator::emit_string_constant(const std::string& value) {
    const std::string name = next_string_name();
    const std::size_t byte_len = value.size() + 1;
    std::ostringstream out;
    out << "@" << name << " = private unnamed_addr constant [" << byte_len << " x i8] c\"" << escape_bytes(value)
        << "\\00\"\n";
    globals_ += out.str();
    return name + "|" + std::to_string(byte_len);
}

AddressValue LLVMIRGenerator::emit_address(const Expr& expr) {
    if (const auto* node = dynamic_cast<const VariableExpr*>(&expr)) {
        return {variables_.at(node->name), variable_types_.at(node->name)};
    }
    if (const auto* node = dynamic_cast<const FieldAccessExpr*>(&expr)) {
        const AddressValue base = emit_address(*node->object);
        const auto field_index = struct_field_indices_.at(base.type.name).at(node->field);
        const Type field_type = structs_.at(base.type.name).fields[field_index].type;
        const std::string reg = next_register();
        body_ += "  " + reg + " = getelementptr inbounds " + llvm_type(base.type) + ", ptr " + base.address + ", i32 0, i32 " +
                 std::to_string(field_index) + "\n";
        return {reg, field_type};
    }
    if (const auto* node = dynamic_cast<const IndexExpr*>(&expr)) {
        const AddressValue base = emit_address(*node->object);
        const TypedIRValue index = emit_expr(*node->index);
        emit_bounds_check(index.ir, base.type.array_size);
        const std::string reg = next_register();
        body_ += "  " + reg + " = getelementptr inbounds " + llvm_type(base.type) + ", ptr " + base.address +
                 ", i32 0, i64 " + index.ir + "\n";
        return {reg, *base.type.element_type};
    }
    const TypedIRValue value = emit_expr(expr);
    const std::string storage = next_register();
    body_ += "  " + storage + " = alloca " + llvm_type(value.type) + "\n";
    body_ += "  store " + llvm_type(value.type) + " " + value.ir + ", ptr " + storage + "\n";
    return {storage, value.type};
}

TypedIRValue LLVMIRGenerator::emit_expr(const Expr& expr) {
    if (const auto* node = dynamic_cast<const IntegerExpr*>(&expr)) {
        return {std::to_string(node->value), Type::int_type()};
    }
    if (const auto* node = dynamic_cast<const BoolExpr*>(&expr)) {
        return {node->value ? "1" : "0", Type::bool_type()};
    }
    if (const auto* node = dynamic_cast<const StringExpr*>(&expr)) {
        const std::string constant = emit_string_constant(node->value);
        const auto sep = constant.find('|');
        const std::string global_name = constant.substr(0, sep);
        const std::size_t len = static_cast<std::size_t>(std::stoull(constant.substr(sep + 1)));
        const std::string reg = next_register();
        body_ += "  " + reg + " = getelementptr inbounds [" + std::to_string(len) + " x i8], ptr @" + global_name +
                 ", i64 0, i64 0\n";
        return {reg, Type::string_type()};
    }
    if (const auto* node = dynamic_cast<const ArrayLiteralExpr*>(&expr)) {
        const TypedIRValue first = emit_expr(*node->elements[0]);
        const Type array_type = Type::array_type(first.type, node->elements.size());
        const std::string storage = next_register();
        body_ += "  " + storage + " = alloca " + llvm_type(array_type) + "\n";
        const std::string first_ptr = next_register();
        body_ += "  " + first_ptr + " = getelementptr inbounds " + llvm_type(array_type) + ", ptr " + storage +
                 ", i32 0, i64 0\n";
        body_ += "  store " + llvm_type(first.type) + " " + first.ir + ", ptr " + first_ptr + "\n";
        for (std::size_t i = 1; i < node->elements.size(); ++i) {
            const TypedIRValue value = emit_expr(*node->elements[i]);
            const std::string element_ptr = next_register();
            body_ += "  " + element_ptr + " = getelementptr inbounds " + llvm_type(array_type) + ", ptr " + storage +
                     ", i32 0, i64 " + std::to_string(i) + "\n";
            body_ += "  store " + llvm_type(value.type) + " " + value.ir + ", ptr " + element_ptr + "\n";
        }
        const std::string reg = next_register();
        body_ += "  " + reg + " = load " + llvm_type(array_type) + ", ptr " + storage + "\n";
        return {reg, array_type};
    }
    if (const auto* node = dynamic_cast<const StructLiteralExpr*>(&expr)) {
        const Type struct_type = Type::struct_type(node->struct_name);
        const std::string storage = next_register();
        body_ += "  " + storage + " = alloca " + llvm_type(struct_type) + "\n";
        for (const auto& field : node->fields) {
            const std::size_t index = struct_field_indices_.at(node->struct_name).at(field.name);
            const Type field_type = structs_.at(node->struct_name).fields[index].type;
            const TypedIRValue value = emit_expr(*field.value);
            const std::string field_ptr = next_register();
            body_ += "  " + field_ptr + " = getelementptr inbounds " + llvm_type(struct_type) + ", ptr " + storage +
                     ", i32 0, i32 " + std::to_string(index) + "\n";
            body_ += "  store " + llvm_type(field_type) + " " + value.ir + ", ptr " + field_ptr + "\n";
        }
        const std::string reg = next_register();
        body_ += "  " + reg + " = load " + llvm_type(struct_type) + ", ptr " + storage + "\n";
        return {reg, struct_type};
    }
    if (dynamic_cast<const VariableExpr*>(&expr) || dynamic_cast<const FieldAccessExpr*>(&expr) ||
        dynamic_cast<const IndexExpr*>(&expr)) {
        const AddressValue address = emit_address(expr);
        const std::string reg = next_register();
        body_ += "  " + reg + " = load " + llvm_type(address.type) + ", ptr " + address.address + "\n";
        return {reg, address.type};
    }
    if (const auto* node = dynamic_cast<const UnaryExpr*>(&expr)) {
        const TypedIRValue value = emit_expr(*node->expr);
        if (node->op == "!") {
            const std::string reg = next_register();
            body_ += "  " + reg + " = xor i1 " + value.ir + ", true\n";
            return {reg, Type::bool_type()};
        }
    }
    if (const auto* node = dynamic_cast<const BinaryExpr*>(&expr)) {
        const TypedIRValue left = emit_expr(*node->left);
        const TypedIRValue right = emit_expr(*node->right);
        const std::string reg = next_register();

        if (node->op == "&&") {
            body_ += "  " + reg + " = and i1 " + left.ir + ", " + right.ir + "\n";
            return {reg, Type::bool_type()};
        }
        if (node->op == "||") {
            body_ += "  " + reg + " = or i1 " + left.ir + ", " + right.ir + "\n";
            return {reg, Type::bool_type()};
        }
        if (node->op == "==" || node->op == "!=") {
            const std::string cmp = node->op == "==" ? "eq" : "ne";
            body_ += "  " + reg + " = icmp " + cmp + " " + llvm_type(left.type) + " " + left.ir + ", " + right.ir + "\n";
            return {reg, Type::bool_type()};
        }
        if (node->op == "<" || node->op == "<=" || node->op == ">" || node->op == ">=") {
            std::string cmp;
            if (node->op == "<") cmp = "slt";
            if (node->op == "<=") cmp = "sle";
            if (node->op == ">") cmp = "sgt";
            if (node->op == ">=") cmp = "sge";
            body_ += "  " + reg + " = icmp " + cmp + " i64 " + left.ir + ", " + right.ir + "\n";
            return {reg, Type::bool_type()};
        }
        if (node->op == "+" && left.type == Type::string_type()) {
            body_ += "  " + reg + " = call ptr @pinggen_concat(ptr " + left.ir + ", ptr " + right.ir + ")\n";
            return {reg, Type::string_type()};
        }

        std::string op;
        if (node->op == "+") op = "add";
        if (node->op == "-") op = "sub";
        if (node->op == "*") op = "mul";
        if (node->op == "/") op = "sdiv";
        if (node->op == "%") op = "srem";
        body_ += "  " + reg + " = " + op + " i64 " + left.ir + ", " + right.ir + "\n";
        return {reg, Type::int_type()};
    }
    if (const auto* node = dynamic_cast<const CallExpr*>(&expr)) {
        if (node->callee == "io::println") {
            const TypedIRValue arg = emit_expr(*node->args[0]);
            if (arg.type == Type::int_type()) {
                const std::string fmt_reg = next_register();
                const std::string call_reg = next_register();
                body_ += "  " + fmt_reg + " = getelementptr inbounds [6 x i8], ptr @.fmt.int, i64 0, i64 0\n";
                body_ += "  " + call_reg + " = call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", i64 " + arg.ir + ")\n";
            } else {
                const std::string fmt_reg = next_register();
                const std::string call_reg = next_register();
                body_ += "  " + fmt_reg + " = getelementptr inbounds [4 x i8], ptr @.fmt.str, i64 0, i64 0\n";
                body_ += "  " + call_reg + " = call i32 (ptr, ...) @printf(ptr " + fmt_reg + ", ptr " + arg.ir + ")\n";
            }
            return {"0", Type::void_type()};
        }

        std::vector<TypedIRValue> args;
        for (const auto& arg : node->args) {
            args.push_back(emit_expr(*arg));
        }

        const Type return_type = function_return_types_.at(node->callee);
        std::string call_args;
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (i != 0) {
                call_args += ", ";
            }
            call_args += llvm_type(args[i].type) + " " + args[i].ir;
        }

        if (return_type == Type::void_type()) {
            body_ += "  call void @" + node->callee + "(" + call_args + ")\n";
            return {"0", Type::void_type()};
        }

        const std::string reg = next_register();
        body_ += "  " + reg + " = call " + llvm_type(return_type) + " @" + node->callee + "(" + call_args + ")\n";
        return {reg, return_type};
    }
    if (const auto* node = dynamic_cast<const MethodCallExpr*>(&expr)) {
        std::vector<TypedIRValue> args;
        std::string lowered_name;
        bool is_mutating = false;
        if (const auto* object_var = dynamic_cast<const VariableExpr*>(node->object.get())) {
            const Type object_type = variable_types_.at(object_var->name);
            lowered_name = object_type.name + "__" + node->method;
            is_mutating = mutating_methods_.at(lowered_name);
        } else {
            const TypedIRValue object_value = emit_expr(*node->object);
            lowered_name = object_value.type.name + "__" + node->method;
            is_mutating = mutating_methods_.at(lowered_name);
            args.push_back(object_value);
        }

        if (is_mutating) {
            const AddressValue self_addr = emit_address(*node->object);
            args.clear();
            args.push_back({self_addr.address, self_addr.type});
        } else if (args.empty()) {
            args.push_back(emit_expr(*node->object));
        }
        for (const auto& arg : node->args) {
            args.push_back(emit_expr(*arg));
        }

        const Type return_type = function_return_types_.at(lowered_name);
        std::string call_args;
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (i != 0) {
                call_args += ", ";
            }
            if (is_mutating && i == 0) {
                call_args += "ptr " + args[i].ir;
            } else {
                call_args += llvm_type(args[i].type) + " " + args[i].ir;
            }
        }

        if (return_type == Type::void_type()) {
            body_ += "  call void @" + lowered_name + "(" + call_args + ")\n";
            return {"0", Type::void_type()};
        }

        const std::string reg = next_register();
        body_ += "  " + reg + " = call " + llvm_type(return_type) + " @" + lowered_name + "(" + call_args + ")\n";
        return {reg, return_type};
    }

    return {"0", Type::void_type()};
}

bool LLVMIRGenerator::emit_block(const std::vector<std::unique_ptr<Stmt>>& body) {
    for (const auto& stmt : body) {
        if (emit_stmt(*stmt)) {
            return true;
        }
    }
    return false;
}

bool LLVMIRGenerator::emit_stmt(const Stmt& stmt) {
    if (const auto* node = dynamic_cast<const LetStmt*>(&stmt)) {
        const TypedIRValue value = emit_expr(*node->initializer);
        const std::string storage = next_register();
        body_ += "  " + storage + " = alloca " + llvm_type(value.type) + "\n";
        body_ += "  store " + llvm_type(value.type) + " " + value.ir + ", ptr " + storage + "\n";
        variables_[node->name] = storage;
        variable_types_[node->name] = value.type;
        return false;
    }
    if (const auto* node = dynamic_cast<const AssignStmt*>(&stmt)) {
        const TypedIRValue value = emit_expr(*node->value);
        const Type type = variable_types_.at(node->name);
        body_ += "  store " + llvm_type(type) + " " + value.ir + ", ptr " + variables_.at(node->name) + "\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const FieldAssignStmt*>(&stmt)) {
        const auto object_address = emit_address(*node->object);
        const std::size_t index = struct_field_indices_.at(object_address.type.name).at(node->field);
        const Type field_type = structs_.at(object_address.type.name).fields[index].type;
        const TypedIRValue value = emit_expr(*node->value);
        const std::string field_ptr = next_register();
        body_ += "  " + field_ptr + " = getelementptr inbounds " + llvm_type(object_address.type) + ", ptr " +
                 object_address.address + ", i32 0, i32 " + std::to_string(index) + "\n";
        body_ += "  store " + llvm_type(field_type) + " " + value.ir + ", ptr " + field_ptr + "\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const IndexAssignStmt*>(&stmt)) {
        const AddressValue object_address = emit_address(*node->object);
        const TypedIRValue index = emit_expr(*node->index);
        emit_bounds_check(index.ir, object_address.type.array_size);
        const Type element_type = *object_address.type.element_type;
        const TypedIRValue value = emit_expr(*node->value);
        const std::string element_ptr = next_register();
        body_ += "  " + element_ptr + " = getelementptr inbounds " + llvm_type(object_address.type) + ", ptr " +
                 object_address.address + ", i32 0, i64 " + index.ir + "\n";
        body_ += "  store " + llvm_type(element_type) + " " + value.ir + ", ptr " + element_ptr + "\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const ExprStmt*>(&stmt)) {
        emit_expr(*node->expr);
        return false;
    }
    if (const auto* node = dynamic_cast<const IfStmt*>(&stmt)) {
        const TypedIRValue condition = emit_expr(*node->condition);
        const std::string then_label = next_label("if_then");
        const std::string else_label = next_label("if_else");
        const std::string end_label = next_label("if_end");
        body_ += "  br i1 " + condition.ir + ", label %" + then_label + ", label %" + else_label + "\n";

        body_ += then_label + ":\n";
        const bool then_returns = emit_block(node->then_body);
        if (!then_returns) {
            body_ += "  br label %" + end_label + "\n";
        }

        body_ += else_label + ":\n";
        const bool has_else = !node->else_body.empty();
        const bool else_returns = has_else && emit_block(node->else_body);
        if (!else_returns) {
            body_ += "  br label %" + end_label + "\n";
        }

        if (!(then_returns && has_else && else_returns)) {
            body_ += end_label + ":\n";
        }
        return then_returns && has_else && else_returns;
    }
    if (const auto* node = dynamic_cast<const WhileStmt*>(&stmt)) {
        const std::string cond_label = next_label("while_cond");
        const std::string body_label = next_label("while_body");
        const std::string end_label = next_label("while_end");

        body_ += "  br label %" + cond_label + "\n";
        body_ += cond_label + ":\n";
        const TypedIRValue condition = emit_expr(*node->condition);
        body_ += "  br i1 " + condition.ir + ", label %" + body_label + ", label %" + end_label + "\n";
        body_ += body_label + ":\n";

        continue_labels_.push_back(cond_label);
        break_labels_.push_back(end_label);
        const bool body_returns = emit_block(node->body);
        continue_labels_.pop_back();
        break_labels_.pop_back();

        if (!body_returns) {
            body_ += "  br label %" + cond_label + "\n";
        }
        body_ += end_label + ":\n";
        return false;
    }
    if (const auto* node = dynamic_cast<const ForStmt*>(&stmt)) {
        const TypedIRValue start = emit_expr(*node->start);
        const TypedIRValue end = emit_expr(*node->end);
        const std::string loop_storage = next_register();
        body_ += "  " + loop_storage + " = alloca i64\n";
        body_ += "  store i64 " + start.ir + ", ptr " + loop_storage + "\n";

        const std::string cond_label = next_label("for_cond");
        const std::string body_label = next_label("for_body");
        const std::string step_label = next_label("for_step");
        const std::string end_label = next_label("for_end");

        body_ += "  br label %" + cond_label + "\n";
        body_ += cond_label + ":\n";
        const std::string current_reg = next_register();
        const std::string cond_reg = next_register();
        body_ += "  " + current_reg + " = load i64, ptr " + loop_storage + "\n";
        body_ += "  " + cond_reg + " = icmp slt i64 " + current_reg + ", " + end.ir + "\n";
        body_ += "  br i1 " + cond_reg + ", label %" + body_label + ", label %" + end_label + "\n";
        body_ += body_label + ":\n";

        const auto previous_var = variables_.find(node->name);
        const auto previous_type = variable_types_.find(node->name);
        const bool had_previous_var = previous_var != variables_.end();
        const bool had_previous_type = previous_type != variable_types_.end();
        const std::string previous_storage = had_previous_var ? previous_var->second : "";
        const Type previous_type_value = had_previous_type ? previous_type->second : Type::void_type();

        variables_[node->name] = loop_storage;
        variable_types_[node->name] = Type::int_type();
        continue_labels_.push_back(step_label);
        break_labels_.push_back(end_label);
        const bool body_returns = emit_block(node->body);
        continue_labels_.pop_back();
        break_labels_.pop_back();
        if (had_previous_var) {
            variables_[node->name] = previous_storage;
        } else {
            variables_.erase(node->name);
        }
        if (had_previous_type) {
            variable_types_[node->name] = previous_type_value;
        } else {
            variable_types_.erase(node->name);
        }

        if (!body_returns) {
            body_ += "  br label %" + step_label + "\n";
        }
        body_ += step_label + ":\n";
        const std::string step_current = next_register();
        const std::string next_value = next_register();
        body_ += "  " + step_current + " = load i64, ptr " + loop_storage + "\n";
        body_ += "  " + next_value + " = add i64 " + step_current + ", 1\n";
        body_ += "  store i64 " + next_value + ", ptr " + loop_storage + "\n";
        body_ += "  br label %" + cond_label + "\n";
        body_ += end_label + ":\n";
        return false;
    }
    if (dynamic_cast<const BreakStmt*>(&stmt)) {
        body_ += "  br label %" + break_labels_.back() + "\n";
        return true;
    }
    if (dynamic_cast<const ContinueStmt*>(&stmt)) {
        body_ += "  br label %" + continue_labels_.back() + "\n";
        return true;
    }
    if (const auto* node = dynamic_cast<const ReturnStmt*>(&stmt)) {
        if (!node->value) {
            if (current_function_name_ == "main") {
                body_ += "  ret i32 0\n";
            } else if (current_return_type_ == Type::void_type()) {
                body_ += "  ret void\n";
            } else if (current_return_type_ == Type::bool_type()) {
                body_ += "  ret i1 0\n";
            } else if (current_return_type_ == Type::int_type()) {
                body_ += "  ret i64 0\n";
            }
            return true;
        }

        const TypedIRValue value = emit_expr(*node->value);
        if (current_function_name_ == "main") {
            const std::string reg = next_register();
            body_ += "  " + reg + " = trunc i64 " + value.ir + " to i32\n";
            body_ += "  ret i32 " + reg + "\n";
        } else {
            body_ += "  ret " + llvm_type(value.type) + " " + value.ir + "\n";
        }
        return true;
    }
    return false;
}

std::string LLVMIRGenerator::llvm_type(const Type& type) const {
    switch (type.kind) {
        case TypeKind::Int: return "i64";
        case TypeKind::Bool: return "i1";
        case TypeKind::String: return "ptr";
        case TypeKind::Void: return "void";
        case TypeKind::Struct: return "%struct." + type.name;
        case TypeKind::Array: return "[" + std::to_string(type.array_size) + " x " + llvm_type(*type.element_type) + "]";
    }
    return "void";
}

std::string LLVMIRGenerator::next_label(const std::string& prefix) {
    return prefix + "." + std::to_string(++label_counter_);
}

void LLVMIRGenerator::reset_function_state() {
    body_.clear();
    variables_.clear();
    variable_types_.clear();
    register_counter_ = 0;
}

std::string LLVMIRGenerator::next_register() {
    return "%" + std::to_string(++register_counter_);
}

std::string LLVMIRGenerator::next_string_name() {
    return ".str." + std::to_string(++string_counter_);
}

std::string LLVMIRGenerator::escape_bytes(const std::string& value) {
    std::ostringstream out;
    for (unsigned char c : value) {
        switch (c) {
            case '\n': out << "\\0A"; break;
            case '\t': out << "\\09"; break;
            case '\"': out << "\\22"; break;
            case '\\': out << "\\5C"; break;
            default:
                if (c >= 32 && c <= 126) {
                    out << static_cast<char>(c);
                } else {
                    const char* digits = "0123456789ABCDEF";
                    out << '\\' << digits[(c >> 4) & 0xF] << digits[c & 0xF];
                }
        }
    }
    return out.str();
}

}  // namespace pinggen
