[package]
name = "invalid_dependency_std_name"
version = "0.1.0"

[build]
name = "invalid_dependency_std_name"
entry = "src/main.pg"
output = "build/invalid_dependency_std_name"

[[dependency]]
name = "std"
path = "../path_dependency_shared"
